[package]
name = "sman"
authors = ["ghashy <obsidian.musicwork@gmail.com>"]
version = "0.1.0"
edition = "2021"
description = "Automate deployment, rolling updating, health checking, etc."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3
