#!/bin/bash

# Define the paths to the nginx configuration file and the temporary file
nginx_conf="$HOME/nginx.conf"

# Function to add backend servers to nginx configuration
add_servers() {
  local address="$@"
  sed -i "/.*upstream ghashy_backend {/a server $address" "$nginx_conf"
}

# Function to remove backend servers from nginx configuration
remove_servers() {
    local address="$@"
    sed -i "/$address;/d" "$nginx_conf"
}

while getopts ":-:" opt; do 
  case "${opt}" in
    -)
      case "${OPTARG}" in
        add)
          # call add function
          ;;
        remove)
          # call remove function
          ;;
        *)
          echo "Failed"
          ;;
      esac
      ;;
    \?)
      echo "Oops! -$OPTARG isn't a valid option for this script."
      exit 1
      ;;
    :)
      echo "Oops! Option -$OPTARG requires an argument"
      exit 1
      ;;
  esac
done

# Restart nginx to apply the changes
service nginx restart


