#!/bin/bash

# Set the color code
GREEN='\033[0;32m'

# Reset the color code
NC='\033[0m'

# Variables
local_dir="build"
remote_user="ghashy"
remote_host="151.248.121.67"
remote_dir="/sites/advocat"
ssh_port="39000"

upload_build() {
    # Copy the file using scp to the new version directory
    scp -r -P "$ssh_port" -i '~/.ssh/id_rsa' "$local_dir" "$remote_user@$remote_host:$remote_dir/"

    # Check if the dir was copied successfully
    if [ $? -eq 0 ]; then
        echo "Build uploaded successfully."

        ssh -p "$ssh_port" -i '~/.ssh/id_rsa' "$remote_user@$remote_host" "cd $remote_dir && chgrp -R site_owners build && chmod g+w -R build && rm -r stable_build"

        if [ $? -eq 0 ]; then
            echo -e "${GREEN}Permissions updated, old build directory removed successfully!${NC}"
            ssh -p "$ssh_port" "$remote_user@$remote_host" "cd $remote_dir &&mv build stable_build"

            if [ $? -eq 0 ]; then
                echo -e "${GREEN}Finished.${NC}"
            else
                echo "Failed to remane directory to \"stable_build\"."
            fi
        else
            echo "Can't remove old build directory."
        fi
    else
        echo "Error uploading file."
    fi
}

upload_build