#!/usr/bin/env bash

# IMPORTANT: Installed `inotify-tool` is required

SCRIPT_NAME="watch_script"
WATCH_DIR="../"

# Watch for create, modify, and delete events
inotifywait --monitor --event create,modify,delete $WATCH_DIR |
while read -r directory event file; do
   echo "$(date) - $SCRIPT_NAME: Action notification: $event - $file"
   # Code to star rolling update
done
